language: node_js
sudo: false
cache:
  - npm
  - yarn
os:
  - linux
node_js:
  - '10'
services:
  - docker
addons:
  ssh_known_hosts: 60.205.219.85
  apt:
    packages:
      - docker-ce
notifications:
  email:
    on_failure: always

before_install:
  - openssl aes-256-cbc -K $encrypted_69dfbb00aaa2_key -iv $encrypted_69dfbb00aaa2_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - docker --version

script:
  # - npm run build
  # 设定服务器启动脚本权限
  - chmod 777 ./deploy/startup.sh
  # 将nginx配置文件拷贝到服务器nginx目录
  - scp -P 15678 -o StrictHostKeyChecking=no -r ./plan-box.conf root@60.205.219.85:/alidata/server/nginx/conf/vhosts
  # 将build目录下部分文件拷贝到服务器dist目录, 目前需要app shell, favicon
  #- scp -o StrictHostKeyChecking=no -p ./build/index.html ./build/favicon.ico root@60.205.219.85:/mynode/plan-box-ci/dist
  # 将deploy目录下文件拷贝到服务器deploy目录
  - scp -P 15678 -o StrictHostKeyChecking=no -r -p ./deploy/* root@60.205.219.85:/mynode/plan-box-ci/deploy
  # 登录docker hub
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  # 创建后端镜像tag
  - docker build -t caaalabash/plan-box:$TRAVIS_BRANCH-$TRAVIS_BUILD_ID-BE .
  # 上传镜像语法: docker push repository:tag
  - docker push caaalabash/plan-box:$TRAVIS_BRANCH-$TRAVIS_BUILD_ID-BE
after_success:
  # 执行服务器脚本 传递构建Id
  - ssh -p 15678 root@60.205.219.85 -o StrictHostKeyChecking=no "/mynode/plan-box-ci/deploy/startup.sh $TRAVIS_BRANCH-$TRAVIS_BUILD_ID"
  # 重启nginx
  - ssh -p 15678 root@60.205.219.85 -o StrictHostKeyChecking=no "nginx -s reload"
