language: node_js
sudo: false
os:
- linux
node_js:
- '10'
addons:
  ssh_known_hosts: 60.205.219.85
notifications:
  email:
    on_failure: always
before_install:
- openssl aes-256-cbc -K $encrypted_69dfbb00aaa2_key -iv $encrypted_69dfbb00aaa2_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
script:
- npm run build
- scp -o StrictHostKeyChecking=no -r ./build root@60.205.219.85:/alidata/www/plan-box/backup
after_success:
- ssh root@60.205.219.85 -o StrictHostKeyChecking=no '/mynode/plan-box-ci/start.sh'
