version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: plan-box-backend
    ports:
      - 7778:7778
    volumes:
      - /etc/localtime:/etc/localtime
    network_mode: host
    restart: unless-stopped
