version: "3"
services:
  # Node 后端服务
  backend:
    # 选择的镜像为 caaalabash/plan-box + 环境变量VUE_BLOG_TAG + BE后缀
    image: caaalabash/plan-box:${PLAN_BOX_TAG}-BE
    container_name: plan-box-backend
    # 挂载环境变量
    env_file:
      - /mynode/plan-box-ci/plan-box.env
    volumes:
      - /etc/localtime:/etc/localtime
      - /mynode/plan-box-ci/dist:/app/frontend/dist
    network_mode: host
    restart: unless-stopped
